import { Match, ContestTier, LeaderboardEntry, FantasyWalletState, Player } from './types';

export const mockPlayersIndia: Player[] = [
  {
    id: 'ind-1',
    name: 'Rohit Sharma',
    shortName: 'R. Sharma',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BAT',
    credits: 10.0,
    points: 245,
    stats: {
      matches: 265,
      runs: 10866,
      wickets: 9,
      strikeRate: 91.8,
      recentPoints: [88, 42, 115, 34, 92],
      averagePoints: 74.2,
      selectionRate: 86.4,
    },
  },
  {
    id: 'ind-2',
    name: 'Virat Kohli',
    shortName: 'V. Kohli',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BAT',
    credits: 10.5,
    points: 310,
    stats: {
      matches: 295,
      runs: 13906,
      wickets: 5,
      strikeRate: 93.5,
      recentPoints: [124, 76, 142, 54, 98],
      averagePoints: 98.8,
      selectionRate: 94.2,
    },
  },
  {
    id: 'ind-3',
    name: 'Shubman Gill',
    shortName: 'S. Gill',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BAT',
    credits: 9.0,
    points: 198,
    stats: {
      matches: 47,
      runs: 2328,
      wickets: 0,
      strikeRate: 101.7,
      recentPoints: [64, 28, 85, 112, 45],
      averagePoints: 66.8,
      selectionRate: 72.1,
    },
  },
  {
    id: 'ind-4',
    name: 'Suryakumar Yadav',
    shortName: 'S. Yadav',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BAT',
    credits: 8.5,
    points: 165,
    stats: {
      matches: 71,
      runs: 2341,
      wickets: 0,
      strikeRate: 167.8,
      recentPoints: [55, 92, 18, 44, 70],
      averagePoints: 55.8,
      selectionRate: 58.6,
    },
  },
  {
    id: 'ind-5',
    name: 'Rishabh Pant',
    shortName: 'R. Pant',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'WK',
    credits: 9.0,
    points: 215,
    stats: {
      matches: 31,
      runs: 865,
      wickets: 0,
      strikeRate: 106.7,
      recentPoints: [74, 52, 89, 41, 62],
      averagePoints: 63.6,
      selectionRate: 81.3,
    },
  },
  {
    id: 'ind-6',
    name: 'KL Rahul',
    shortName: 'KL Rahul',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'WK',
    credits: 8.5,
    points: 180,
    stats: {
      matches: 77,
      runs: 2851,
      wickets: 0,
      strikeRate: 87.6,
      recentPoints: [48, 62, 35, 78, 51],
      averagePoints: 54.8,
      selectionRate: 64.5,
    },
  },
  {
    id: 'ind-7',
    name: 'Hardik Pandya',
    shortName: 'H. Pandya',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'AR',
    credits: 9.5,
    points: 260,
    stats: {
      matches: 89,
      runs: 1820,
      wickets: 84,
      strikeRate: 110.4,
      economy: 5.56,
      recentPoints: [85, 110, 45, 92, 78],
      averagePoints: 82.0,
      selectionRate: 89.1,
    },
  },
  {
    id: 'ind-8',
    name: 'Ravindra Jadeja',
    shortName: 'R. Jadeja',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'AR',
    credits: 9.0,
    points: 230,
    stats: {
      matches: 197,
      runs: 2756,
      wickets: 220,
      strikeRate: 85.3,
      economy: 4.88,
      recentPoints: [91, 65, 84, 72, 59],
      averagePoints: 74.2,
      selectionRate: 78.4,
    },
  },
  {
    id: 'ind-9',
    name: 'Jasprit Bumrah',
    shortName: 'J. Bumrah',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BOWL',
    credits: 9.5,
    points: 290,
    stats: {
      matches: 89,
      runs: 85,
      wickets: 149,
      economy: 4.59,
      recentPoints: [96, 120, 75, 88, 105],
      averagePoints: 96.8,
      selectionRate: 92.7,
    },
  },
  {
    id: 'ind-10',
    name: 'Mohammed Siraj',
    shortName: 'M. Siraj',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BOWL',
    credits: 8.5,
    points: 190,
    stats: {
      matches: 44,
      runs: 35,
      wickets: 71,
      economy: 5.18,
      recentPoints: [62, 85, 34, 76, 50],
      averagePoints: 61.4,
      selectionRate: 68.2,
    },
  },
  {
    id: 'ind-11',
    name: 'Kuldeep Yadav',
    shortName: 'K. Yadav',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BOWL',
    credits: 8.5,
    points: 210,
    stats: {
      matches: 106,
      runs: 175,
      wickets: 172,
      economy: 5.02,
      recentPoints: [78, 92, 45, 88, 64],
      averagePoints: 73.4,
      selectionRate: 74.9,
    },
  },
  {
    id: 'ind-12',
    name: 'Arshdeep Singh',
    shortName: 'A. Singh',
    teamId: 'team-ind',
    teamCode: 'IND',
    role: 'BOWL',
    credits: 8.0,
    points: 155,
    stats: {
      matches: 8,
      runs: 10,
      wickets: 14,
      economy: 5.4,
      recentPoints: [48, 55, 62, 38, 70],
      averagePoints: 54.6,
      selectionRate: 41.2,
    },
  },
];

export const mockPlayersAustralia: Player[] = [
  {
    id: 'aus-1',
    name: 'Travis Head',
    shortName: 'T. Head',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'BAT',
    credits: 9.5,
    points: 275,
    stats: {
      matches: 65,
      runs: 2432,
      wickets: 18,
      strikeRate: 103.8,
      recentPoints: [110, 84, 45, 95, 82],
      averagePoints: 83.2,
      selectionRate: 88.5,
    },
  },
  {
    id: 'aus-2',
    name: 'David Warner',
    shortName: 'D. Warner',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'BAT',
    credits: 9.0,
    points: 210,
    stats: {
      matches: 161,
      runs: 6932,
      wickets: 0,
      strikeRate: 97.2,
      recentPoints: [65, 82, 38, 74, 55],
      averagePoints: 62.8,
      selectionRate: 75.3,
    },
  },
  {
    id: 'aus-3',
    name: 'Steve Smith',
    shortName: 'S. Smith',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'BAT',
    credits: 9.0,
    points: 220,
    stats: {
      matches: 158,
      runs: 5446,
      wickets: 28,
      strikeRate: 87.5,
      recentPoints: [58, 72, 85, 42, 68],
      averagePoints: 65.0,
      selectionRate: 71.4,
    },
  },
  {
    id: 'aus-4',
    name: 'Mitchell Marsh',
    shortName: 'M. Marsh',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'AR',
    credits: 9.0,
    points: 235,
    stats: {
      matches: 89,
      runs: 2672,
      wickets: 56,
      strikeRate: 95.8,
      economy: 5.48,
      recentPoints: [82, 45, 94, 65, 78],
      averagePoints: 72.8,
      selectionRate: 79.2,
    },
  },
  {
    id: 'aus-5',
    name: 'Glenn Maxwell',
    shortName: 'G. Maxwell',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'AR',
    credits: 9.5,
    points: 260,
    stats: {
      matches: 142,
      runs: 3934,
      wickets: 74,
      strikeRate: 126.9,
      economy: 5.04,
      recentPoints: [95, 118, 42, 88, 67],
      averagePoints: 82.0,
      selectionRate: 84.7,
    },
  },
  {
    id: 'aus-6',
    name: 'Marcus Stoinis',
    shortName: 'M. Stoinis',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'AR',
    credits: 8.5,
    points: 175,
    stats: {
      matches: 70,
      runs: 1490,
      wickets: 48,
      strikeRate: 93.2,
      economy: 5.8,
      recentPoints: [45, 68, 52, 70, 39],
      averagePoints: 54.8,
      selectionRate: 53.1,
    },
  },
  {
    id: 'aus-7',
    name: 'Josh Inglis',
    shortName: 'J. Inglis',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'WK',
    credits: 8.5,
    points: 170,
    stats: {
      matches: 26,
      runs: 542,
      wickets: 0,
      strikeRate: 96.5,
      recentPoints: [52, 64, 41, 78, 35],
      averagePoints: 54.0,
      selectionRate: 59.8,
    },
  },
  {
    id: 'aus-8',
    name: 'Alex Carey',
    shortName: 'A. Carey',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'WK',
    credits: 8.0,
    points: 145,
    stats: {
      matches: 76,
      runs: 1890,
      wickets: 0,
      strikeRate: 88.4,
      recentPoints: [42, 38, 55, 48, 60],
      averagePoints: 48.6,
      selectionRate: 38.2,
    },
  },
  {
    id: 'aus-9',
    name: 'Pat Cummins',
    shortName: 'P. Cummins',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'BOWL',
    credits: 9.0,
    points: 240,
    stats: {
      matches: 88,
      runs: 450,
      wickets: 141,
      economy: 5.22,
      recentPoints: [78, 85, 62, 94, 71],
      averagePoints: 78.0,
      selectionRate: 83.4,
    },
  },
  {
    id: 'aus-10',
    name: 'Mitchell Starc',
    shortName: 'M. Starc',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'BOWL',
    credits: 9.0,
    points: 250,
    stats: {
      matches: 121,
      runs: 520,
      wickets: 236,
      economy: 5.15,
      recentPoints: [85, 102, 58, 89, 76],
      averagePoints: 82.0,
      selectionRate: 86.9,
    },
  },
  {
    id: 'aus-11',
    name: 'Adam Zampa',
    shortName: 'A. Zampa',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'BOWL',
    credits: 8.5,
    points: 205,
    stats: {
      matches: 99,
      runs: 120,
      wickets: 169,
      economy: 5.51,
      recentPoints: [68, 74, 52, 85, 60],
      averagePoints: 67.8,
      selectionRate: 72.0,
    },
  },
  {
    id: 'aus-12',
    name: 'Josh Hazlewood',
    shortName: 'J. Hazlewood',
    teamId: 'team-aus',
    teamCode: 'AUS',
    role: 'BOWL',
    credits: 8.5,
    points: 195,
    stats: {
      matches: 85,
      runs: 95,
      wickets: 132,
      economy: 4.65,
      recentPoints: [64, 78, 45, 82, 59],
      averagePoints: 65.6,
      selectionRate: 66.7,
    },
  },
];

export const mockMatches: Match[] = [
  {
    id: 'match-ind-aus-1',
    title: 'India vs Australia',
    series: 'ICC Champions Trophy 2026',
    format: 'ODI',
    status: 'live',
    startTime: '2026-08-29T14:00:00Z',
    deadlineTime: '2026-08-29T13:55:00Z',
    venue: 'Melbourne Cricket Ground',
    city: 'Melbourne',
    teamA: {
      id: 'team-ind',
      name: 'India',
      code: 'IND',
      flag: '🇮🇳',
      color: '#1E3A8A',
      secondaryColor: '#3B82F6',
    },
    teamB: {
      id: 'team-aus',
      name: 'Australia',
      code: 'AUS',
      flag: '🇦🇺',
      color: '#CA8A04',
      secondaryColor: '#FACC15',
    },
    totalPrizePool: 150000,
    contestCount: 14,
    liveScore: {
      currentInnings: 2,
      battingTeamId: 'team-aus',
      bowlingTeamId: 'team-ind',
      battingScore: {
        runs: 182,
        wickets: 5,
        overs: 34.2,
      },
      targetRuns: 288,
      crr: 5.3,
      rrr: 6.77,
      currentBatsmen: [
        {
          playerId: 'aus-5',
          name: 'Glenn Maxwell',
          runs: 48,
          balls: 32,
          fours: 4,
          sixes: 2,
          strikeRate: 150.0,
          isOut: false,
        },
        {
          playerId: 'aus-9',
          name: 'Pat Cummins',
          runs: 14,
          balls: 18,
          fours: 1,
          sixes: 0,
          strikeRate: 77.8,
          isOut: false,
        },
      ],
      currentBowler: {
        playerId: 'ind-9',
        name: 'Jasprit Bumrah',
        overs: 7.2,
        maidens: 1,
        runs: 28,
        wickets: 3,
        economy: 3.82,
      },
      recentBalls: ['1', '0', 'W', '4', '1', '2', '0', '6'],
      recentBallEvents: [
        {
          ball: '34.2',
          bowlerName: 'Jasprit Bumrah',
          batsmanName: 'Glenn Maxwell',
          runs: 1,
          isWicket: false,
          isBoundary: false,
          isSix: false,
          commentary: 'Slower yorker on middle, worked away to deep square leg for a single.',
        },
        {
          ball: '34.1',
          bowlerName: 'Jasprit Bumrah',
          batsmanName: 'Pat Cummins',
          runs: 0,
          isWicket: false,
          isBoundary: false,
          isSix: false,
          commentary: 'Pacy delivery angling in, blocked solidly back to bowler.',
        },
        {
          ball: '33.6',
          bowlerName: 'Kuldeep Yadav',
          batsmanName: 'Mitchell Marsh',
          runs: 0,
          isWicket: true,
          isBoundary: false,
          isSix: false,
          commentary: 'OUT! Clean bowled! Wrong-un rips through the gate to crash into off stump.',
        },
      ],
      partnerships: {
        runs: 38,
        balls: 42,
        batsman1: 'Glenn Maxwell (28)',
        batsman2: 'Pat Cummins (10)',
      },
    },
    players: [...mockPlayersIndia, ...mockPlayersAustralia],
  },
  {
    id: 'match-eng-sa-2',
    title: 'England vs South Africa',
    series: 'ICC World T20 Championship',
    format: 'T20',
    status: 'upcoming',
    startTime: '2026-08-29T19:30:00Z',
    deadlineTime: '2026-08-29T19:25:00Z',
    venue: "Lord's Cricket Ground",
    city: 'London',
    teamA: {
      id: 'team-eng',
      name: 'England',
      code: 'ENG',
      flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
      color: '#DC2626',
      secondaryColor: '#EF4444',
    },
    teamB: {
      id: 'team-sa',
      name: 'South Africa',
      code: 'SA',
      flag: '🇿🇦',
      color: '#15803D',
      secondaryColor: '#22C55E',
    },
    totalPrizePool: 95000,
    contestCount: 9,
    players: [...mockPlayersIndia, ...mockPlayersAustralia].map((p, idx) => ({
      ...p,
      id: `eng-sa-${idx + 1}`,
      teamId: idx < 12 ? 'team-eng' : 'team-sa',
      teamCode: idx < 12 ? 'ENG' : 'SA',
    })),
  },
  {
    id: 'match-nz-pak-3',
    title: 'New Zealand vs Pakistan',
    series: 'Super Series Tri-Nation Cup',
    format: 'T20',
    status: 'upcoming',
    startTime: '2026-08-30T09:00:00Z',
    deadlineTime: '2026-08-30T08:55:00Z',
    venue: 'Eden Park',
    city: 'Auckland',
    teamA: {
      id: 'team-nz',
      name: 'New Zealand',
      code: 'NZ',
      flag: '🇳🇿',
      color: '#0F172A',
      secondaryColor: '#334155',
    },
    teamB: {
      id: 'team-pak',
      name: 'Pakistan',
      code: 'PAK',
      flag: '🇵🇰',
      color: '#047857',
      secondaryColor: '#10B981',
    },
    totalPrizePool: 75000,
    contestCount: 8,
    players: [...mockPlayersIndia, ...mockPlayersAustralia].map((p, idx) => ({
      ...p,
      id: `nz-pak-${idx + 1}`,
      teamId: idx < 12 ? 'team-nz' : 'team-pak',
      teamCode: idx < 12 ? 'NZ' : 'PAK',
    })),
  },
  {
    id: 'match-ind-pak-4',
    title: 'India vs Pakistan',
    series: 'Asia Cup Final',
    format: 'T20',
    status: 'completed',
    startTime: '2026-08-27T14:30:00Z',
    deadlineTime: '2026-08-27T14:25:00Z',
    venue: 'Dubai International Cricket Stadium',
    city: 'Dubai',
    teamA: {
      id: 'team-ind',
      name: 'India',
      code: 'IND',
      flag: '🇮🇳',
      color: '#1E3A8A',
      secondaryColor: '#3B82F6',
    },
    teamB: {
      id: 'team-pak',
      name: 'Pakistan',
      code: 'PAK',
      flag: '🇵🇰',
      color: '#047857',
      secondaryColor: '#10B981',
    },
    totalPrizePool: 250000,
    contestCount: 20,
    liveScore: {
      currentInnings: 2,
      battingTeamId: 'team-pak',
      bowlingTeamId: 'team-ind',
      battingScore: {
        runs: 168,
        wickets: 9,
        overs: 20.0,
      },
      targetRuns: 182,
      crr: 8.4,
      currentBatsmen: [],
      currentBowler: {
        playerId: 'ind-9',
        name: 'Jasprit Bumrah',
        overs: 4.0,
        maidens: 1,
        runs: 16,
        wickets: 3,
        economy: 4.0,
      },
      recentBalls: ['1', 'W', '2', '0', '1', 'W'],
      recentBallEvents: [],
      partnerships: {
        runs: 12,
        balls: 8,
        batsman1: 'Naseem Shah (8)',
        batsman2: 'Haris Rauf (4)',
      },
    },
    players: [...mockPlayersIndia, ...mockPlayersAustralia],
  },
];

export const mockContestTiers: ContestTier[] = [
  {
    id: 'contest-gl-1',
    matchId: 'match-ind-aus-1',
    name: 'Mega Grand League',
    type: 'Grand League',
    entryFeeUVBE: 100,
    maxParticipants: 1000,
    currentParticipants: 842,
    totalPrizePoolUVBE: 90000,
    winnerPercentage: 65,
    maxTeamsPerUser: 11,
    firstPrizeUVBE: 25000,
    isGuaranteed: true,
    prizeBreakdown: [
      { rankRange: 'Rank 1', prizeUVBE: 25000, percentage: 27.7 },
      { rankRange: 'Rank 2', prizeUVBE: 12000, percentage: 13.3 },
      { rankRange: 'Rank 3', prizeUVBE: 7500, percentage: 8.3 },
      { rankRange: 'Rank 4 - 10', prizeUVBE: 2000, percentage: 15.5 },
      { rankRange: 'Rank 11 - 50', prizeUVBE: 400, percentage: 17.7 },
      { rankRange: 'Rank 51 - 650', prizeUVBE: 150, percentage: 17.5 },
    ],
  },
  {
    id: 'contest-h2h-1',
    matchId: 'match-ind-aus-1',
    name: 'High Roller Head-to-Head',
    type: 'Head-to-Head',
    entryFeeUVBE: 100,
    maxParticipants: 2,
    currentParticipants: 1,
    totalPrizePoolUVBE: 180,
    winnerPercentage: 50,
    maxTeamsPerUser: 1,
    firstPrizeUVBE: 180,
    isGuaranteed: true,
    prizeBreakdown: [{ rankRange: 'Rank 1', prizeUVBE: 180, percentage: 100 }],
  },
  {
    id: 'contest-sl-1',
    matchId: 'match-ind-aus-1',
    name: 'Pro Small League',
    type: 'Small League',
    entryFeeUVBE: 100,
    maxParticipants: 10,
    currentParticipants: 7,
    totalPrizePoolUVBE: 900,
    winnerPercentage: 30,
    maxTeamsPerUser: 2,
    firstPrizeUVBE: 500,
    isGuaranteed: true,
    prizeBreakdown: [
      { rankRange: 'Rank 1', prizeUVBE: 500, percentage: 55.5 },
      { rankRange: 'Rank 2', prizeUVBE: 250, percentage: 27.7 },
      { rankRange: 'Rank 3', prizeUVBE: 150, percentage: 16.8 },
    ],
  },
  {
    id: 'contest-gl-2',
    matchId: 'match-ind-aus-1',
    name: 'Super 50 Pool',
    type: 'Small League',
    entryFeeUVBE: 250,
    maxParticipants: 50,
    currentParticipants: 39,
    totalPrizePoolUVBE: 11250,
    winnerPercentage: 40,
    maxTeamsPerUser: 3,
    firstPrizeUVBE: 4000,
    isGuaranteed: true,
    prizeBreakdown: [
      { rankRange: 'Rank 1', prizeUVBE: 4000, percentage: 35.5 },
      { rankRange: 'Rank 2', prizeUVBE: 2200, percentage: 19.5 },
      { rankRange: 'Rank 3 - 5', prizeUVBE: 1000, percentage: 26.6 },
      { rankRange: 'Rank 6 - 20', prizeUVBE: 350, percentage: 18.4 },
    ],
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    teamName: 'Cricket Kings XI',
    userAddress: '0x71C...4982',
    points: 612.5,
    captainName: 'Virat Kohli (C)',
    viceCaptainName: 'Jasprit Bumrah (VC)',
    isUser: false,
    estimatedPrizeUVBE: 25000,
    movement: 'same',
  },
  {
    rank: 2,
    teamName: 'Vijay Super XI',
    userAddress: '0x32A...8109',
    points: 598.0,
    captainName: 'Glenn Maxwell (C)',
    viceCaptainName: 'Rohit Sharma (VC)',
    isUser: false,
    estimatedPrizeUVBE: 12000,
    movement: 'up',
  },
  {
    rank: 3,
    teamName: 'My UV Champions (You)',
    userAddress: '0x9aF...3312',
    points: 586.0,
    captainName: 'Virat Kohli (C)',
    viceCaptainName: 'Ravindra Jadeja (VC)',
    isUser: true,
    estimatedPrizeUVBE: 7500,
    movement: 'up',
  },
  {
    rank: 4,
    teamName: 'Power Hitters XI',
    userAddress: '0x5Bc...9021',
    points: 574.0,
    captainName: 'Travis Head (C)',
    viceCaptainName: 'Hardik Pandya (VC)',
    isUser: false,
    estimatedPrizeUVBE: 2000,
    movement: 'down',
  },
  {
    rank: 5,
    teamName: 'Aussie Strikers',
    userAddress: '0x14D...7723',
    points: 561.5,
    captainName: 'Mitchell Starc (C)',
    viceCaptainName: 'Rishabh Pant (VC)',
    isUser: false,
    estimatedPrizeUVBE: 2000,
    movement: 'same',
  },
  {
    rank: 6,
    teamName: 'Master Blasters',
    userAddress: '0x88F...4120',
    points: 549.0,
    captainName: 'Rohit Sharma (C)',
    viceCaptainName: 'Pat Cummins (VC)',
    isUser: false,
    estimatedPrizeUVBE: 2000,
    movement: 'up',
  },
  {
    rank: 7,
    teamName: 'Spin Wizards',
    userAddress: '0x43C...6218',
    points: 532.5,
    captainName: 'Kuldeep Yadav (C)',
    viceCaptainName: 'Adam Zampa (VC)',
    isUser: false,
    estimatedPrizeUVBE: 2000,
    movement: 'down',
  },
  {
    rank: 8,
    teamName: 'Boundary Hunters',
    userAddress: '0x92E...1044',
    points: 518.0,
    captainName: 'Suryakumar Yadav (C)',
    viceCaptainName: 'Glenn Maxwell (VC)',
    isUser: false,
    estimatedPrizeUVBE: 2000,
    movement: 'same',
  },
];

export const mockFantasyWallet: FantasyWalletState = {
  availableUVBE: 12450.0,
  fantasyLockedUVBE: 300.0,
  fantasyRewardsUVBE: 650.0,
  totalFantasyEntries: 6,
  totalWonUVBE: 1450.0,
};

export const mockUserFantasyPoints = [
  { name: 'Virat Kohli', points: 124, role: 'BAT', multiplier: 2.0, total: 248 },
  { name: 'Jasprit Bumrah', points: 96, role: 'BOWL', multiplier: 1.0, total: 96 },
  { name: 'Ravindra Jadeja', points: 91, role: 'AR', multiplier: 1.5, total: 136.5 },
  { name: 'Rishabh Pant', points: 74, role: 'WK', multiplier: 1.0, total: 74 },
  { name: 'Hardik Pandya', points: 42, role: 'AR', multiplier: 1.0, total: 42 },
  { name: 'Glenn Maxwell', points: 68, role: 'AR', multiplier: 1.0, total: 68 },
];
