const fs = require('fs');
const path = require('path');

const CONTRACT_NAMES = [
  'ProtocolDirectory',
  'OracleManager',
  'ChainlinkOracleProvider',
  'Treasury',
  'FeeManager',
  'CustodyVault',
  'LiquidityManager',
  'UVBEV2',
  'SwapAdapter',
  'StrategyManager',
  'PortfolioManager',
  'UnifyVaultController',
  'CostBasisManagerV2',
  'P2PEscrowV2',
  'PerformanceManager',
  'Marketplace',
];

const PROTOCOL_OUT_DIR = path.resolve(__dirname, '../packages/protocol/out');
const TARGET_FILE = path.resolve(__dirname, '../apps/web-v2/lib/deployment/generatedArtifacts.ts');

const artifacts = {};

for (const name of CONTRACT_NAMES) {
  const jsonPath = path.join(PROTOCOL_OUT_DIR, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(jsonPath)) {
    console.error(`Missing artifact for ${name} at ${jsonPath}`);
    process.exit(1);
  }
  const content = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  artifacts[name] = {
    contractName: name,
    abi: content.abi,
    bytecode: content.bytecode.object.startsWith('0x')
      ? content.bytecode.object
      : `0x${content.bytecode.object}`,
  };
}

const fileContent = `/**
 * AUTOGENERATED FROM FOUNDRY ARTIFACTS
 * DO NOT EDIT MANUALLY. Run: node scripts/generate_deployment_artifacts.js
 */
import type { Abi } from 'viem';

export interface ContractArtifact {
  contractName: string;
  abi: Abi;
  bytecode: \`0x\${string}\`;
}

export const DEPLOYMENT_ARTIFACTS: Record<string, ContractArtifact> = ${JSON.stringify(artifacts, null, 2)};
`;

fs.mkdirSync(path.dirname(TARGET_FILE), { recursive: true });
fs.writeFileSync(TARGET_FILE, fileContent, 'utf8');
console.log(`Successfully generated deployment artifacts at ${TARGET_FILE}`);
