export const CONTROLLER_ABI = [
  {
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'minSharesOut', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'deposit',
    outputs: [
      {
        components: [
          { name: 'assetId', type: 'bytes32' },
          { name: 'asset', type: 'address' },
          { name: 'receiver', type: 'address' },
          { name: 'depositAmount', type: 'uint256' },
          { name: 'rawPrice', type: 'uint256' },
          { name: 'normalizedPrice', type: 'uint256' },
          { name: 'sharesPreview', type: 'uint256' },
          { name: 'protocolFee', type: 'uint256' },
          { name: 'netDeposit', type: 'uint256' },
          { name: 'timestamp', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'shares', type: 'uint256' },
      { name: 'minAssetsOut', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'deadline', type: 'uint256' },
    ],
    name: 'redeem',
    outputs: [{ name: 'netAssets', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'minSharesOut', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'getDepositQuote',
    outputs: [
      {
        components: [
          { name: 'assetId', type: 'bytes32' },
          { name: 'asset', type: 'address' },
          { name: 'receiver', type: 'address' },
          { name: 'depositAmount', type: 'uint256' },
          { name: 'rawPrice', type: 'uint256' },
          { name: 'normalizedPrice', type: 'uint256' },
          { name: 'sharesPreview', type: 'uint256' },
          { name: 'protocolFee', type: 'uint256' },
          { name: 'netDeposit', type: 'uint256' },
          { name: 'timestamp', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'getRedeemQuote',
    outputs: [
      {
        components: [
          { name: 'asset', type: 'address' },
          { name: 'receiver', type: 'address' },
          { name: 'shares', type: 'uint256' },
          { name: 'grossCollateral', type: 'uint256' },
          { name: 'grossValueUSD', type: 'uint256' },
          { name: 'protocolFee', type: 'uint256' },
          { name: 'netPayout', type: 'uint256' },
          { name: 'timestamp', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'asset', type: 'address' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'getRedeemQuote',
    outputs: [
      {
        components: [
          { name: 'asset', type: 'address' },
          { name: 'receiver', type: 'address' },
          { name: 'shares', type: 'uint256' },
          { name: 'grossCollateral', type: 'uint256' },
          { name: 'grossValueUSD', type: 'uint256' },
          { name: 'protocolFee', type: 'uint256' },
          { name: 'netPayout', type: 'uint256' },
          { name: 'timestamp', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'shares', type: 'uint256' },
    ],
    name: 'previewRedeem',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'previewDeposit',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maxDeposit',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'swapSlippageBps',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getDepositFeeBps',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRedeemFeeBps',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'slippageBps_', type: 'uint256' }],
    name: 'setSwapSlippageBps',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'emergencyPause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'resume',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'strategyManager',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },

  // --- Events ---
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'depositAmount', type: 'uint256' },
      { indexed: false, name: 'fee', type: 'uint256' },
      { indexed: false, name: 'targetAssets', type: 'address[]' },
      { indexed: false, name: 'assetsBought', type: 'uint256[]' },
      { indexed: false, name: 'sharesMinted', type: 'uint256' },
      { indexed: false, name: 'navAfter', type: 'uint256' },
    ],
    name: 'DepositExecuted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'sharesBurned', type: 'uint256' },
      { indexed: false, name: 'targetAssets', type: 'address[]' },
      { indexed: false, name: 'assetsSold', type: 'uint256[]' },
      { indexed: false, name: 'fee', type: 'uint256' },
      { indexed: false, name: 'usdcReturned', type: 'uint256' },
      { indexed: false, name: 'navAfter', type: 'uint256' },
    ],
    name: 'RedeemExecuted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'receiver', type: 'address' },
      { indexed: true, name: 'asset', type: 'address' },
      { indexed: false, name: 'grossDeposit', type: 'uint256' },
      { indexed: false, name: 'protocolFee', type: 'uint256' },
      { indexed: false, name: 'netDeposit', type: 'uint256' },
      { indexed: false, name: 'sharesMinted', type: 'uint256' },
    ],
    name: 'DepositCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'receiver', type: 'address' },
      { indexed: true, name: 'asset', type: 'address' },
      { indexed: false, name: 'sharesBurned', type: 'uint256' },
      { indexed: false, name: 'grossAssets', type: 'uint256' },
      { indexed: false, name: 'protocolFee', type: 'uint256' },
      { indexed: false, name: 'netAssets', type: 'uint256' },
    ],
    name: 'RedeemCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'payer', type: 'address' },
      { indexed: true, name: 'asset', type: 'address' },
      { indexed: false, name: 'feeAmount', type: 'uint256' },
    ],
    name: 'ProtocolFeeCollected',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: 'caller', type: 'address' }],
    name: 'EmergencyPaused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: 'caller', type: 'address' }],
    name: 'EmergencyResumed',
    type: 'event',
  },

  // --- Errors ---
  { inputs: [{ name: 'target', type: 'address' }], name: 'NotAContract', type: 'error' },
  {
    inputs: [
      { name: 'deadline', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
    ],
    name: 'DeadlineExpired',
    type: 'error',
  },
  { inputs: [], name: 'MathCalculationOverflow', type: 'error' },
  { inputs: [], name: 'ZeroAddressDetected', type: 'error' },
  {
    inputs: [
      { name: 'requested', type: 'uint256' },
      { name: 'maxAllowed', type: 'uint256' },
    ],
    name: 'DepositExceedsTxLimit',
    type: 'error',
  },
  {
    inputs: [
      { name: 'newTotal', type: 'uint256' },
      { name: 'cap', type: 'uint256' },
    ],
    name: 'DailyDepositCapExceeded',
    type: 'error',
  },
  {
    inputs: [
      { name: 'requested', type: 'uint256' },
      { name: 'maxAllowed', type: 'uint256' },
    ],
    name: 'RedeemExceedsTxLimit',
    type: 'error',
  },
  {
    inputs: [
      { name: 'newTotal', type: 'uint256' },
      { name: 'cap', type: 'uint256' },
    ],
    name: 'DailyRedeemCapExceeded',
    type: 'error',
  },
  { inputs: [{ name: 'assetId', type: 'bytes32' }], name: 'AssetNotSupported', type: 'error' },
  {
    inputs: [
      { name: 'expected', type: 'uint256' },
      { name: 'actual', type: 'uint256' },
      { name: 'minAllowed', type: 'uint256' },
    ],
    name: 'InsufficientSwapOutput',
    type: 'error',
  },
  {
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'price', type: 'int256' },
    ],
    name: 'OraclePriceNegative',
    type: 'error',
  },
  { inputs: [], name: 'RegistryIsFrozen', type: 'error' },
  { inputs: [], name: 'EnforcedPause', type: 'error' },
  { inputs: [], name: 'ExpectedPause', type: 'error' },
  { inputs: [{ name: 'caller', type: 'address' }], name: 'UnauthorizedCaller', type: 'error' },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'required', type: 'uint256' },
      { name: 'available', type: 'uint256' },
    ],
    name: 'InsufficientBalance',
    type: 'error',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'required', type: 'uint256' },
      { name: 'available', type: 'uint256' },
    ],
    name: 'InsufficientAllowance',
    type: 'error',
  },
  {
    inputs: [
      { name: 'expected', type: 'uint256' },
      { name: 'actual', type: 'uint256' },
    ],
    name: 'SlippageExceeded',
    type: 'error',
  },
] as const;
